General testing stuff


Current is landmark systematisation

In [1]:
import napari
import spatialdata 
import sopa
import napari_spatialdata
import spatialdata_plot 

d:\Dom\Virtual_Environments\napari_registration_project\.venv\Lib\site-packages\dask\dataframe\__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(
d:\Dom\Virtual_Environments\napari_registration_project\.venv\Lib\site-packages\xarray_schema\__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
d:\Dom\Virtual_Environments\napari_registration_project\.venv\Lib\site-packages\spatialdata\_core\query\relational_query.py:530: FutureWarning: functools.partial will be a method descriptor in fu

In [5]:
xenX = "D:/Dom/Fibrosis project/4th year data/pheno_xen_fullres_images/morphology_focus_scaledX_dapi.ome.tif"
xenXY = "D:/Dom/Fibrosis project/4th year data/pheno_xen_fullres_images/morphology_focus_scaledXY_dapi.ome.tif"
xenPM = "D:/Dom/Fibrosis project/4th year data/pheno_xen_fullres_images/morphology_focus_ds_dapi.ome.tif"

xenX = sopa.io.ome_tif(xenX)
xenXY = sopa.io.ome_tif(xenXY)
xenPM = sopa.io.ome_tif(xenPM)

In [ ]:
from napari_spatialdata import Interactive
Interactive([xenX, xenXY, xenPM]).run()

2025-11-24 15:38:52.027 | WARNING  | napari_spatialdata._viewer:__init__:57 - Due to Shift-L being used as shortcut in napari, it is being deprecated and might not link a new layer to an existing SpatialData object in the viewer. Please use ⌘-L on MacOS or else Ctrl-L.


2025-11-24 15:39:05.864 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:39:05.866 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:39:11.147 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:39:11.150 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:39:11.151 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:39:19.284 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:39:19.287 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:39:19.288 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:40:04.943 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-24 15:40:04.950 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updati

In [ ]:
import pandas as pd
import numpy as np
from spatialdata.models import PointsModel
from spatialdata.transformations import Identity

# Read your CSV file
landmarks_df = pd.read_csv("D:/Dom/Fibrosis project/4th year data/xen_pheno_registration/systematising landmarks/Landmark csvs/3_xen_space.csv")
pheno_landmarks_df = pd.read_csv("D:/Dom/Fibrosis project/4th year data/xen_pheno_registration/systematising landmarks/Landmark csvs/3_pheno_space.csv")

# Extract coordinates (axis-1 = x, axis-2 = y)
# SpatialData expects coordinates in (y, x) order for 2D points
coords = landmarks_df[['axis-2', 'axis-1']].values
pheno_coords = pheno_landmarks_df[['axis-2', 'axis-1']].values

# Create a DataFrame in the format expected by PointsModel
# PointsModel expects columns: ['x', 'y'] or ['z', 'y', 'x'] for 3D
points_df = pd.DataFrame({
    'y': landmarks_df['axis-1'].values,
    'x': landmarks_df['axis-2'].values
})

pheno_points_df = pd.DataFrame({
    'y': pheno_landmarks_df['axis-1'].values,
    'x': pheno_landmarks_df['axis-2'].values
})

# Create the points element with transformation to global coordinate system
points_element = PointsModel.parse(
    points_df,
    transformations={"global": Identity()}
)

pheno_points_element = PointsModel.parse(
    pheno_points_df,
    transformations={"global": Identity()}
)

# Add to your xen_image SpatialData object
xen_image.points['xen_landmarks'] = points_element
pheno_image.points['pheno_landmarks'] = pheno_points_element 


In [58]:
import pandas as pd
import numpy as np
from spatialdata.models import PointsModel
from spatialdata.transformations import Identity

# Read your CSV file
landmarks_df = pd.read_csv("D:/Dom/Fibrosis project/4th year data/xen_pheno_registration/systematising landmarks/Landmark csvs/ds30_xen_bi.csv")
pheno_landmarks_df = pd.read_csv("D:/Dom/Fibrosis project/4th year data/xen_pheno_registration/systematising landmarks/Landmark csvs/ds30_pheno_bi.csv")

# Extract coordinates (axis-1 = x, axis-2 = y)
# SpatialData expects coordinates in (y, x) order for 2D points
coords = landmarks_df[['axis-0', 'axis-1']].values
pheno_coords = pheno_landmarks_df[['axis-0', 'axis-1']].values

# Create a DataFrame in the format expected by PointsModel
# PointsModel expects columns: ['x', 'y'] or ['z', 'y', 'x'] for 3D
points_df = pd.DataFrame({
    'y': landmarks_df['axis-1'].values,
    'x': landmarks_df['axis-0'].values
})

pheno_points_df = pd.DataFrame({
    'y': pheno_landmarks_df['axis-1'].values,
    'x': pheno_landmarks_df['axis-0'].values
})

# Create the points element with transformation to global coordinate system
points_element = PointsModel.parse(
    points_df,
    transformations={"global": Identity()}
)

pheno_points_element = PointsModel.parse(
    pheno_points_df,
    transformations={"global": Identity()}
)

# Add to your xen_image SpatialData object
xen_image.points['xen_landmarks'] = points_element
pheno_image.points['pheno_landmarks'] = pheno_points_element 


In [60]:

#registration calculation
from spatialdata.transformations import (
    align_elements_using_landmarks,
    get_transformation_between_landmarks,
)

affine = get_transformation_between_landmarks(
    references_coords=xen_image["xen_landmarks"], moving_coords=pheno_image["pheno_landmarks"]
)
affine
affine = align_elements_using_landmarks(
    references_coords=xen_image["xen_landmarks"], 
    moving_coords=pheno_image["pheno_landmarks"],
    reference_element=xen_image[list(xen_image.images.keys())[0]],
    moving_element=pheno_image["pheno_C12"],
    reference_coordinate_system="global",
    moving_coordinate_system="global",
    new_coordinate_system="aligned",
)
affine

Sequence 
    Identity 
    Affine (x, y -> x, y)
        [ 0.9995803   0.00717712 -4.43859178]
        [-7.17711959e-03  9.99580304e-01  5.90882600e+02]
        [0. 0. 1.]

In [ ]:
xen_image.write("D:/Dom/Fibrosis project/4th year data/xen_pheno_registration/systematising landmarks/aligned objects/ds30_bi_xen.zarr")
pheno_image.write("D:/Dom/Fibrosis project/4th year data/xen_pheno_registration/systematising landmarks/aligned objects/ds30_bi_pheno.zarr")

xen_image.write_transformations()
pheno_image.write_transformations()